sudo: required
language: bash
services:
  - docker
script:
  - cd docker
  - docker build -t ecat/bt-search-docker .
  - docker images
  - docker run -d --name bt-search-docker -p 127.0.0.1:81:80 ecat/bt-search-docker
  - docker ps -a
after_success:
    - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
    - docker push ecat/bt-search-docker
